# Jekyll configuration
source: .
destination: _site
exclude:
  # Dependencies
  - node_modules
  - frontend/node_modules
  - backend/node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  
  # Development files
  - .git
  - .gitignore
  - .env*
  - README.md
  - frontend
  - backend
  - calculator2.html
  - "melkamu wako protfolio and landing page"
  
  # Asset files
  - "*.pdf"
  - "*.txt"
  - scss
  - mail
  
  # Build directories
  - dist
  - build
  - .next
  - .cache
  - .temp

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
baseurl: ""
url: "https://melke27.github.io"

# Collections
collections:
  data:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass configuration
sass:
  style: compressed
  load_paths:
    - assets/css

# Include static files
include:
  - assets
  - assets/css
  - assets/js
  - assets/img
  - assets/lib

# Keep files
keep_files:
  - assets
  - assets/css
  - assets/js
  - assets/img
  - assets/lib 